### ISSUE TITLE
Error trying to create .deb file

### ISSUE THREAD

**Issue by jfabaf** [adelolmo/hd-idle#2] opened 2019-08-13 13:14 UTC
I have Ubuntu 18.04.3 LTS.
Go Version: go version go1.12.7 linux/amd64
I run these commands:

$ mkdir -p $GOPATH/src/github.com/adelolmo
$ cd $GOPATH/src/github.com/adelolmo
$ git clone https://github.com/adelolmo/hd-idle.git
$ cd hd-idle
$ dpkg-buildpackage  -us -uc -b -d

But I get this error:

$ dpkg-buildpackage -us -uc -b -d
_dpkg-buildpackage: info: source package hd-idle
dpkg-buildpackage: info: source version 1.4
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Andoni del Olmo <andoni.delolmo@gmail.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build hd-idle
 fakeroot debian/rules clean
dh clean --buildsystem=golang --with=golang
   dh_auto_clean -O--buildsystem=golang
   debian/rules override_dh_clean
make[1]: Entering directory '/home/user/go/src/github.com/adelolmo/hd-idle'
rm -f debian/debhelper.log
dh_clean
make[1]: Leaving directory '/home/user/go/src/github.com/adelolmo/hd-idle'
 debian/rules build
dh build --buildsystem=golang --with=golang
   dh_update_autotools_config -O--buildsystem=golang
   dh_auto_configure -O--buildsystem=golang
   debian/rules override_dh_auto_build
make[1]: Entering directory '/home/user/go/src/github.com/adelolmo/hd-idle'
dh_auto_build -- -ldflags "-s -w"
build cache is disabled by GOCACHE=off, but required as of Go 1.12
	cd obj-x86_64-linux-gnu && go install -gcflags=\"-trimpath=/home/user/go/src/github.com/adelolmo/hd-idle/obj-x86_64-linux-gnu/src\" -asmflags=\"-trimpath=/home/user/go/src/github.com/adelolmo/hd-idle/obj-x86_64-linux-gnu/src\" -v -p 1 -ldflags "-s -w"
can't load package: package .: no Go files in /home/user/go/src/github.com/adelolmo/hd-idle/obj-x86_64-linux-gnu
dh_auto_build: cd obj-x86_64-linux-gnu && go install -gcflags=\"-trimpath=/home/user/go/src/github.com/adelolmo/hd-idle/obj-x86_64-linux-gnu/src\" -asmflags=\"-trimpath=/home/user/go/src/github.com/adelolmo/hd-idle/obj-x86_64-linux-gnu/src\" -v -p 1 -ldflags "-s -w" returned exit code 1
debian/rules:50: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 1
make[1]: Leaving directory '/home/user/go/src/github.com/adelolmo/hd-idle'
debian/rules:43: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2_

Could you help me please?

Thanks!!

**Comment by adelolmo** [comment] 2019-08-13 15:25
Hi @jfabaf 

could you please run `go build -o /tmp/hd-idle` and paste the output?

**Comment by jfabaf** [comment] 2019-08-13 21:14
Hi @adelolmo,

Command runs with no error and create hd-idle executable file:

$ go build -o /tmp/hd-idle
$ ls -l /tmp/hd-idle

-rwxrwxr-x  1 user user 3253258 ago 13 23:07 hd-idle*

Thank you very much!

**Comment by adelolmo** [comment] 2019-08-15 15:52
Hi @jfabaf 

Than sounds good, but it doesn't solve the issue of not being able of creating the deb package.
I don't want to close the issue before I figure what's the root cause.

Andoni

**Comment by jfabaf** [comment] 2019-08-16 11:24
Hi @adelolmo ,

Thank you very much.
I'd like to install hd-idle from .deb in order to use systemctl to enable hd-idle service.
If you need further information do not hesitate to ask me.

Regards!

**Comment by adelolmo** [comment] 2019-08-16 13:36
Hi @jfabaf 

You can still install one of the provided packages from [releases](https://github.com/adelolmo/hd-idle/releases/latest) if you want.

I'll try to investigate this topic further though.
Will come back to you once I figured what can go wrong here.

**Comment by adelolmo** [comment] 2019-08-29 19:31
Hi @jfabaf 

I was able to reproduce the error by upgrading from go 1.11 to go 1.12.
Now I only have to fix it :)

**Comment by V33m** [comment] 2019-08-29 22:56
I'm in the same boat as jfabaf, the only difference is that there isn't an arm64 version available for downloading from releases.. I'm currently using the armhf package as I suspect there isn't much of a performance difference. Regardless, it would be fantastic if you could build arm64 packages in the future as well given the increasing popularity.

One more thing, under [Wiki](https://github.com/adelolmo/hd-idle/wiki) regarding logfile, it says that 

> ... This option should not be used on systems with more than one disk...

Is the reason for that disks spinup or does it cause instability etc? In my case, I've two disks and I would like to log the activity to a mSD card, which is unaffected of hd-idle, so do you still recommend not to enable logging when using multiple disks?

**Comment by adelolmo** [comment] 2019-08-31 06:27
Hi @V33m 

Regarding arm64 packages I don't have a clear idea how to provide them, but I'll give it a shot.

Regarding the log file: I have pretty much the same set up as you. Some external usb HDs connected to a raspberry pi and the log file written to the SD card. This setup is completely safe and it won't create any spinups.
I will update the documentation to make it clear.

**Comment by V33m** [comment] 2019-08-31 06:48
Perfect!

Thanks for the effort and the awesome job you have done to port hd-idle! :)

**Closed** 2019-08-31 09:54 UTC
Labels: help wanted

**Comment by adelolmo** [comment] 2019-08-31 15:27
@V33m I've added an arm64 deb package to the release. Hope it works.

**Comment by V33m** [comment] 2019-08-31 15:39
Splendid!

I'll try it out later next week and let you know if it doesn't work.

**Comment by jfabaf** [comment] 2019-09-02 07:38
Thank you very much @adelolmo, it works now perfectly!! ;-)
