### ISSUE TITLE
WD Re HDD over USB does not spin down. 

### ISSUE THREAD

**Issue by amo13** [adelolmo/hd-idle#105] opened 2023-10-12 21:34 UTC
My Western Digital Re Disk attached over USB to my Raspberry Pi 2 B does not spin down. Neither when configured with idleTime=5:
```
disk=sda command=ata spunDown=false reads=32 writes=0 idleTime=5 idleDuration=4 spindown=0001-01-01T00:00:00 spinup=2023-10-12T21:15:23 lastIO=2023-10-12T21:15:23
disk=sda command=ata spunDown=false reads=32 writes=0 idleTime=5 idleDuration=5 spindown=0001-01-01T00:00:00 spinup=2023-10-12T21:15:23 lastIO=2023-10-12T21:15:23
sda spindown
disk=sda command=ata spunDown=true reads=32 writes=0 idleTime=5 idleDuration=5 spindown=2023-10-12T21:15:28 spinup=2023-10-12T21:15:23 lastIO=2023-10-12T21:15:23
disk=sda command=ata spunDown=true reads=32 writes=0 idleTime=5 idleDuration=6 spindown=2023-10-12T21:15:28 spinup=2023-10-12T21:15:23 lastIO=2023-10-12T21:15:23
```
...nor with `# hd-idle -t /dev/sda` or `# hd-idle -t /dev/sda -c ata` (both return nothing and nothing happens). 

The HDD *does* spin down though, if I do `# hdparm -y /dev/sda` or `# hdparm -Y /dev/sda`.

**Comment by adelolmo** [comment] 2023-10-13 18:49
@amo13 
Are you by any chance writing the hd-idle log into /dev/sda ?

**Comment by amo13** [comment] 2023-10-14 15:37
Thank you for responding. I appreciate your thoughts on this.

I don't think so. I used the systems unit and copied the log lines from the systemd journal.
The device itself is a luks volume. No partitions, just the full device as luks volume (with btrfs inside). But it was not decrypted or mounted when I tried to spin it down.

Anything else I can double-check or try?

**Comment by adelolmo** [comment] 2023-10-14 15:58
No partitions? That sounds familiar.
I think that's a know issue/limitation https://github.com/adelolmo/hd-idle/issues/70#issuecomment-1488037450
Could you please share your `cat /proc/diskstats`?

**Comment by amo13** [comment] 2023-10-15 17:01
I don't really understand the discussion in #70... Is there no workaround? 
If `hdparm` is able to spin down the disk, why wouldn't `hd-idle` be able to do the same?

Here is the result of diskstats:
```
$ cat /proc/diskstats
   1       0 ram0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1       1 ram1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1       2 ram2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1       3 ram3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1       4 ram4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1       5 ram5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1       6 ram6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1       7 ram7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1       8 ram8 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1       9 ram9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1      10 ram10 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1      11 ram11 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1      12 ram12 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1      13 ram13 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1      14 ram14 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   1      15 ram15 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 179       0 mmcblk0 2710 1733 178235 15005 264 353 11177 37596 0 0 52602 0 0 0 0 0 0
 179       1 mmcblk0p1 93 0 4193 325 1 0 1 2 0 0 327 0 0 0 0 0 0
 179       2 mmcblk0p2 2543 1733 171658 14559 263 353 11176 37594 0 0 52153 0 0 0 0 0 0
   8       0 sda 4 0 32 20 0 0 0 0 0 0 20 0 0 0 0 0 0
```

Thanks for your help with this!

**Comment by adelolmo** [comment] 2023-10-20 19:46
I think that, given what you shared, I'm asking the wrong questions.
To be honest, I can't tell what's going on. The program seems to behave as expected, as shown in the log, but the spin down commands just don't work.

**Comment by amo13** [comment] 2023-10-20 19:53
I'm wondering too. It looks odd to me that `hdparm -y /dev/sda` *does* work though...
Anything we can do or check or try?

**Comment by adelolmo** [comment] 2023-10-20 20:15
Could you share the result of running `# hd-idle -t /dev/sda` and `# hd-idle -t /dev/sda -c ata` with the flag `--verbose`?

**Comment by amo13** [comment] 2023-10-20 20:23
The result is absolutely nothing:

```
[alarm@alarmpi ~]$ lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
sda           8:0    0  1.6T  0 disk 
mmcblk0     179:0    0  3.7G  0 disk 
|-mmcblk0p1 179:1    0  200M  0 part /boot
`-mmcblk0p2 179:2    0  3.5G  0 part /
[alarm@alarmpi ~]$ sudo hd-idle -t /dev/sda --verbose
[sudo] password for alarm: 
[alarm@alarmpi ~]$ sudo hd-idle -t /dev/sda -c ata --verbose
[alarm@alarmpi ~]$ 
```

**Comment by adelolmo** [comment] 2023-10-21 07:52
> The result is absolutely nothing:

Of course, that's because I gave you the wrong commands 🤦‍♂️

Please try again:

- `# hdparm --verbose -y /dev/sda`
- `# hdparm --verbose -Y /dev/sda`

**Comment by amo13** [comment] 2023-10-21 10:42
I see :)
Here we go again:
```
[alarm@alarmpi ~]$ lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
sda           8:0    0  1.6T  0 disk 
mmcblk0     179:0    0  3.7G  0 disk 
|-mmcblk0p1 179:1    0  200M  0 part /boot
`-mmcblk0p2 179:2    0  3.5G  0 part /
[alarm@alarmpi ~]$ sudo hdparm --verbose -y /dev/sda
[sudo] password for alarm: 

/dev/sda:
APT: USB ID = 0x152d:0x2339 (0x100)
APT: Found supported device jmicron
outgoing cdb:  df 10 00 00 01 00 72 0f 00 00 00 fd
SG_IO: ATA_12 status=0x0, host_status=0x0, driver_status=0x0
APT: JMicron Port: 0xA0
 issuing standby command
outgoing cdb:  df 10 00 00 00 00 00 00 00 00 a0 e0
[alarm@alarmpi ~]$ sudo dd if=/dev/sda bs=4096 count=1 of=/dev/null iflag=direct
1+0 records in
1+0 records out
4096 bytes (4.1 kB, 4.0 KiB) copied, 12.2197 s, 0.3 kB/s
[alarm@alarmpi ~]$ sudo hdparm --verbose -Y /dev/sda

/dev/sda:
APT: USB ID = 0x152d:0x2339 (0x100)
APT: Found supported device jmicron
outgoing cdb:  df 10 00 00 01 00 72 0f 00 00 00 fd
SG_IO: ATA_12 status=0x0, host_status=0x0, driver_status=0x0
APT: JMicron Port: 0xA0
 issuing sleep command
outgoing cdb:  df 10 00 00 00 00 00 00 00 00 a0 e6
SG_IO: ATA_12 status=0x0, host_status=0x0, driver_status=0x0
[alarm@alarmpi ~]$
```

**Comment by adelolmo** [comment] 2023-10-21 15:49
The issue is that hd-idle always sends the SG_ATA with length 16, but in your case hdparm is using SG_ATA_12.
I will treat it as a bug in hd-idle and try to come up with a patch to support ATA_12 too.

**Comment by amo13** [comment] 2023-10-21 18:16
Alright, thank you. Looking forward to testing it!
Have you got paypal so I can buy you a coffee?

**Comment by adelolmo** [comment] 2023-10-22 08:11
I've created a pre-release that might solve your issue: https://github.com/adelolmo/hd-idle/releases/tag/v1.21
You should try this command instead: `# hd-idle -t /dev/sda -c ata12`

I still haven't figured out how hdparm decides whether using ata16 or ata12 ¯\_(ツ)_/¯
My idea is to have you trying the pre-release first of all, and if it works I'll spend some more time thinking about how to have hd-idle deciding between ata16 or ata12. I'd like to avoid users having to make that decision if possible.

> Have you got paypal so I can buy you a coffee?

I appreciate the intention, but I prefer not to get any money involved on this.

**Comment by amo13** [comment] 2023-10-22 08:51
Thank you very much for your efforts on this!

Unfortunately, nothing happens with the new command either. Is there anything I can do to help making it work?

If that is of any help, here are some SMART info about the disk:
<details>
<summary># smartctl --info /dev/sda</summary>

```
[alarm@alarmpi build]$ sudo smartctl --info /dev/sda
smartctl 7.4 2023-08-01 r5530 [armv7l-linux-6.1.57-2-rpi-ARCH] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Western Digital Re
Device Model:     WDC WD4000FYYZ-01UL1B2
Serial Number:    WD-WMC130E8PHYT
LU WWN Device Id: 5 0014ee 6051f68d0
Firmware Version: 01.01K03
User Capacity:    4,000,787,030,016 bytes [4.00 TB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    7200 rpm
Device is:        In smartctl database 7.3/5528
ATA Version is:   ATA8-ACS (minor revision not indicated)
SATA Version is:  SATA 3.0, 6.0 Gb/s (current: 1.5 Gb/s)
Local Time is:    Sun Oct 22 08:38:40 2023 UTC
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
```

</details>

<details>
<summary># smartctl --identify /dev/sda</summary>

```
[alarm@alarmpi build]$ sudo smartctl --identify /dev/sda
smartctl 7.4 2023-08-01 r5530 [armv7l-linux-6.1.57-2-rpi-ARCH] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== ATA IDENTIFY DATA ===
Word     Bit     Value   Description

   0      -     0x427a   General configuration
   0     14:8     0x42   Vendor specific [RET-3]
   0      6          1   Not removable controller and/or device [OBS-6]
   0      5:3      0x7   Vendor specific [RET-3]
   0      1          1   Vendor specific [RET-3]

   1      -     0x3fff   Cylinders [OBS-6]

   2      -     0xc837   Specific configuration (0x37c8/738c/8c73/c837)

   3      -     0x0010   Heads [OBS-6]

   6      -     0x003f   Sectors per track [OBS-6]

  10-19   -     .        Serial number (String)
  10-13   .     0x2020:2020:2057:442d  "     WD-"
  14-17   .     0x574d:4331:3330:4538  "WMC130E8"
  18-19   .     0x5048:5954            "PHYT"

  23-26   -     .        Firmware revision (String)
  23-26   .     0x3031:2e30:314b:3033  "01.01K03"

  27-46   -     .        Model number (String)
  27-30   .     0x5744:4320:5744:3430  "WDC WD40"
  31-34   .     0x3030:4659:595a:2d30  "00FYYZ-0"
  35-38   .     0x3155:4c31:4232:2020  "1UL1B2  "
  39-42   .     0x2020:2020:2020:2020  "        "
  43-46   .     0x2020:2020:2020:2020  "        "

  47      -     0x8010   READ/WRITE MULTIPLE support [OBS-ACS-4]
  47     15:8     0x80   Must be set to 0x80
  47      7:0     0x10   Max sectors per DRQ on READ/WRITE MULTIPLE [OBS-ACS-4]

  48      -     0x4000   Trusted Computing feature set options
  48     15:14     0x1   Must be set to 0x1

  49      -     0x2f00   Capabilities
  49     13          1   Standard standby timer values supported
  49     11          1   IORDY supported
  49     10          1   IORDY may be disabled
  49      9          1   LBA supported
  49      8          1   DMA supported

  50      -     0x4001   Capabilities
  50     15:14     0x1   Must be set to 0x1
  50      0          1   Vendor specific minimum standby timer value

  53      -     0x0007   Field validity / Free-fall Control
  53      2          1   Word 88 (Ultra DMA modes) is valid
  53      1          1   Words 64-70 (PIO modes) are valid
  53      0          1   Words 54-58 (CHS) are valid [OBS-6]

  54      -     0x3fff   Current cylinders [OBS-6]

  55      -     0x0010   Current heads [OBS-6]

  56      -     0x003f   Current sectors per track [OBS-6]

  57-58   -     .        Current capacity in sectors (DWord) [OBS-6]
  57-58   .     0xfc10:00fb  (16514064)

  59      -     0x0100   Sanitize Device - READ/WRITE MULTIPLE support
  59      8          1   Bits 7:0 are valid [OBS-ACS-4]

  60-61   -     .        User addressable sectors for 28-bit commands (DWord)
  60-61   .     0xffff:0fff  (268435455)

  63      -     0x0007   Multiword DMA modes
  63      2          1   Multiword DMA mode 2 and below supported
  63      1          1   Multiword DMA mode 1 and below supported
  63      0          1   Multiword DMA mode 0 supported

  64      -     0x0003   PIO modes
  64      1          1   PIO mode 4 supported
  64      0          1   PIO mode 3 supported

  65      -     0x0078   Minimum Multiword DMA cycle time per word in ns

  66      -     0x0078   Recommended Multiword DMA cycle time in ns

  67      -     0x0078   Minimum PIO cycle time without flow control in ns

  68      -     0x0078   Minimum PIO cycle time with IORDY flow control in ns

  75      -     0x001f   Queue depth
  75      4:0     0x1f   Maximum queue depth - 1

  76      -     0x9d0e   Serial ATA capabilities
  76     15          1   READ LOG DMA EXT as equiv to READ LOG EXT supported
  76     12          1   NCQ priority information supported
  76     11          1   Unload while NCQ commands are outstanding supported
  76     10          1   Phy Event Counters supported
  76      8          1   NCQ feature set supported
  76      3          1   SATA Gen3 signaling speed (6.0 Gb/s) supported
  76      2          1   SATA Gen2 signaling speed (3.0 Gb/s) supported
  76      1          1   SATA Gen1 signaling speed (1.5 Gb/s) supported

  77      -     0x0002   Serial ATA additional capabilities
  77      3:1      0x1   Current Serial ATA signal speed

  78      -     0x0044   Serial ATA features supported
  78      6          1   Software Settings Preservation supported
  78      2          1   DMA Setup auto-activation supported

  79      -     0x0040   Serial ATA features enabled
  79      6          1   Software Settings Preservation enabled

  80      -     0x01fe   Major version number
  80      8          1   ATA8-ACS supported
  80      7          1   ATA/ATAPI-7 supported [OBS-ACS-4]
  80      6          1   ATA/ATAPI-6 supported [OBS-ACS-4]
  80      5          1   ATA/ATAPI-5 supported [OBS-ACS-4]
  80      4          1   ATA/ATAPI-4 supported [OBS-8]
  80      3          1   ATA-3 supported [OBS-7]
  80      2          1   ATA-2 supported [OBS-6]
  80      1          1   ATA-1 supported [OBS-5]

  82      -     0x746b   Commands and feature sets supported
  82     14          1   NOP supported
  82     13          1   READ BUFFER supported
  82     12          1   WRITE BUFFER supported
  82     10          1   HPA feature set supported [OBS-ACS-3]
  82      6          1   Read look-ahead supported
  82      5          1   Volatile write cache supported
  82      3          1   Power Management feature set supported
  82      1          1   Security feature set supported
  82      0          1   SMART feature set supported

  83      -     0x7d69   Commands and feature sets supported
  83     15:14     0x1   Must be set to 0x1
  83     13          1   FLUSH CACHE EXT supported
  83     12          1   FLUSH CACHE supported
  83     11          1   DCO feature set supported [OBS-ACS-3]
  83     10          1   48-bit Address feature set supported
  83      8          1   SET MAX security extension supported [OBS-ACS-3]
  83      6          1   SET FEATURES subcommand required to spin-up
  83      5          1   PUIS feature set supported
  83      3          1   APM feature set supported
  83      0          1   DOWNLOAD MICROCODE supported

  84      -     0x6163   Commands and feature sets supported
  84     15:14     0x1   Must be set to 0x1
  84     13          1   IDLE IMMEDIATE with UNLOAD feature supported
  84      8          1   64-bit World Wide Name supported
  84      6          1   WRITE DMA/MULTIPLE FUA EXT supported
  84      5          1   GPL feature set supported
  84      1          1   SMART self-test supported
  84      0          1   SMART error logging supported

  85      -     0x7469   Commands and feature sets supported or enabled
  85     14          1   NOP supported
  85     13          1   READ BUFFER supported
  85     12          1   WRITE BUFFER supported
  85     10          1   HPA feature set supported [OBS-ACS-3]
  85      6          1   Read look-ahead enabled
  85      5          1   Write cache enabled
  85      3          1   Power Management feature set supported
  85      0          1   SMART feature set enabled

  86      -     0xbc49   Commands and feature sets supported or enabled
  86     15          1   Words 119-120 are valid
  86     13          1   FLUSH CACHE EXT supported
  86     12          1   FLUSH CACHE supported
  86     11          1   DCO feature set supported [OBS-ACS-3]
  86     10          1   48-bit Address features set supported
  86      6          1   SET FEATURES subcommand required to spin-up
  86      3          1   APM feature set enabled
  86      0          1   DOWNLOAD MICROCODE supported

  87      -     0x6163   Commands and feature sets supported or enabled
  87     15:14     0x1   Must be set to 0x1
  87     13          1   IDLE IMMEDIATE with UNLOAD FEATURE supported
  87      8          1   64-bit World Wide Name supported
  87      6          1   WRITE DMA/MULTIPLE FUA EXT supported
  87      5          1   GPL feature set supported
  87      1          1   SMART self-test supported
  87      0          1   SMART error logging supported

  88      -     0x407f   Ultra DMA modes
  88     14          1   Ultra DMA mode 6 selected
  88      6          1   Ultra DMA mode 6 and below supported
  88      5          1   Ultra DMA mode 5 and below supported
  88      4          1   Ultra DMA mode 4 and below supported
  88      3          1   Ultra DMA mode 3 and below supported
  88      2          1   Ultra DMA mode 2 and below supported
  88      1          1   Ultra DMA mode 1 and below supported
  88      0          1   Ultra DMA mode 0 supported

  89      -     0x00fa   SECURITY ERASE UNIT time
  89     14:0   0x00fa   SECURITY ERASE UNIT time value

  90      -     0x00fa   ENHANCED SECURITY ERASE UNIT time
  90     14:0   0x00fa   ENHANCED SECURITY ERASE UNIT time value

  91      -     0x00fe   Current APM level
  91      7:0     0xfe   Current APM level value

  92      -     0xfffe   Master Password Identifier

 100-103  -     .        User addressable sectors for 48-bit commands (QWord)
 100-103  .     0xbeb0:d1c0:0001:0000  (7814037168)

 108-111  -     .        World Wide Name
 108-111  .     0x5001:4ee6:051f:68d0

 119      -     0x409c   Commands and feature sets supported
 119     15:14     0x1   Must be set to 0x1
 119      7          1   Extended Power Conditions feature set supported
 119      4          1   DOWNLOAD MICROCODE with mode 3 supported
 119      3          1   READ/WRITE LOG DMA EXT supported
 119      2          1   WRITE UNCORRECTABLE EXT supported

 120      -     0x401c   Commands and feature sets supported or enabled
 120     15:14     0x1   Must be set to 0x1
 120      4          1   DOWNLOAD MICROCODE with mode 3 supported
 120      3          1   READ/WRITE LOG DMA EXT supported
 120      2          1   WRITE UNCORRECTABLE EXT supported

 128      -     0x0021   Security status
 128      5          1   Enhanced security erase supported
 128      0          1   Security supported

 129-159  -     .        Vendor specific
 129-132  .     0x0400:0001:0000:0000
 133-136  .     0x0000:0000:0000:0000
 137-140  .     0x0000:0000:0000:0000
 141-144  .     0x0000:0004:0000:0000
 145-159  .     0x0000:0000:0000:00...

 206      -     0x70bd   SCT Command Transport
 206     15:12     0x7   Vendor specific
 206      7          1   Reserved for Serial ATA
 206      5          1   SCT Data Tables supported
 206      4          1   SCT Feature Control supported
 206      3          1   SCT Error Recovery Control supported
 206      2          1   SCT Write Same supported
 206      0          1   SCT Command Transport supported

 217      -     0x1c20   Nominal media rotation rate

 222      -     0x103e   Transport major version number
 222     15:12     0x1   Type: 0x1 = Serial  | 0x0 = Parallel | 0xe = PCIe
 222      5          1   SATA 3.0
 222      4          1   SATA 2.6
 222      3          1   SATA 2.5
 222      2          1   SATA II: Extensions
 222      1          1   SATA 1.0a           | ATA/ATAPI-7 [OBS-ACS-5]

 234      -     0x0001   Minimum blocks per DOWNLOAD MICROCODE mode 3 command

 235      -     0x1000   Maximum blocks per DOWNLOAD MICROCODE mode 3 command

 255      -     0x04a5   Integrity word
 255     15:8     0x04   Checksum
 255      7:0     0xa5   Signature
```

</details>
<details>
<summary># smartctl --all /dev/sda</summary>

```
[alarm@alarmpi build]$ sudo smartctl --all /dev/sda
smartctl 7.4 2023-08-01 r5530 [armv7l-linux-6.1.57-2-rpi-ARCH] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Western Digital Re
Device Model:     WDC WD4000FYYZ-01UL1B2
Serial Number:    WD-WMC130E8PHYT
LU WWN Device Id: 5 0014ee 6051f68d0
Firmware Version: 01.01K03
User Capacity:    4,000,787,030,016 bytes [4.00 TB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    7200 rpm
Device is:        In smartctl database 7.3/5528
ATA Version is:   ATA8-ACS (minor revision not indicated)
SATA Version is:  SATA 3.0, 6.0 Gb/s (current: 1.5 Gb/s)
Local Time is:    Sun Oct 22 08:42:54 2023 UTC
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

General SMART Values:
Offline data collection status:  (0x84)	Offline data collection activity
					was suspended by an interrupting command from host.
					Auto Offline Data Collection: Enabled.
Self-test execution status:      (   0)	The previous self-test routine completed
					without error or no self-test has ever 
					been run.
Total time to complete Offline 
data collection: 		(47220) seconds.
Offline data collection
capabilities: 			 (0x7b) SMART execute Offline immediate.
					Auto Offline data collection on/off support.
					Suspend Offline collection upon new
					command.
					Offline surface scan supported.
					Self-test supported.
					Conveyance Self-test supported.
					Selective Self-test supported.
SMART capabilities:            (0x0003)	Saves SMART data before entering
					power-saving mode.
					Supports SMART auto save timer.
Error logging capability:        (0x01)	Error logging supported.
					General Purpose Logging supported.
Short self-test routine 
recommended polling time: 	 (   2) minutes.
Extended self-test routine
recommended polling time: 	 ( 510) minutes.
Conveyance self-test routine
recommended polling time: 	 (   5) minutes.
SCT capabilities: 	       (0x70bd)	SCT Status supported.
					SCT Error Recovery Control supported.
					SCT Feature Control supported.
					SCT Data Table supported.

SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x002f   200   200   051    Pre-fail  Always       -       0
  3 Spin_Up_Time            0x0027   148   143   021    Pre-fail  Always       -       11600
  4 Start_Stop_Count        0x0032   100   100   000    Old_age   Always       -       305
  5 Reallocated_Sector_Ct   0x0033   200   200   140    Pre-fail  Always       -       0
  7 Seek_Error_Rate         0x002e   200   200   000    Old_age   Always       -       0
  9 Power_On_Hours          0x0032   040   040   000    Old_age   Always       -       44270
 10 Spin_Retry_Count        0x0032   100   100   000    Old_age   Always       -       0
 11 Calibration_Retry_Count 0x0032   100   253   000    Old_age   Always       -       0
 12 Power_Cycle_Count       0x0032   100   100   000    Old_age   Always       -       92
183 Runtime_Bad_Block       0x0032   100   100   000    Old_age   Always       -       0
192 Power-Off_Retract_Count 0x0032   200   200   000    Old_age   Always       -       43
193 Load_Cycle_Count        0x0032   200   200   000    Old_age   Always       -       261
194 Temperature_Celsius     0x0022   115   086   000    Old_age   Always       -       37
196 Reallocated_Event_Count 0x0032   200   200   000    Old_age   Always       -       0
197 Current_Pending_Sector  0x0032   200   200   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0030   200   200   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x0032   200   200   000    Old_age   Always       -       0
200 Multi_Zone_Error_Rate   0x0008   200   200   000    Old_age   Offline      -       0

SMART Error Log Version: 1
No Errors Logged

SMART Self-test log structure revision number 1
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Conveyance offline  Completed without error       00%     26549         -
# 2  Short offline       Completed without error       00%     26549         -

SMART Selective self-test log data structure revision number 1
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS
    1        0        0  Not_testing
    2        0        0  Not_testing
    3        0        0  Not_testing
    4        0        0  Not_testing
    5        0        0  Not_testing
Selective self-test flags (0x0):
  After scanning selected spans, do NOT read-scan remainder of disk.
If Selective self-test is pending on power-up, resume after 0 minute delay.

The above only provides legacy SMART information - try 'smartctl -x' for more
```

</details>

**Comment by adelolmo** [comment] 2023-10-24 18:33
I had a second look at the output of the command `sudo hdparm --verbose -y /dev/sda`.
There seem to be two ata commands send:
1. `df 10 00 00 01 00 72 0f 00 00 00 fd`
1. `df 10 00 00 00 00 00 00 00 00 a0 e0`

The second one is the standby command, but the first one looks like something specific for your device (jmicron).
I backed new pre-release packages with a version that has these commands hardcoded with the commands above. 
Could you please give it a try and let me know if it works? Just run `# hd-idle -t /dev/sda -c ata12`

**Comment by amo13** [comment] 2023-10-26 05:33
Amazing! I can confirm that it does work now. And it outputs
```
outgoing cdb:  df 10 00 00 01 00 72 0f 00 00 00 fd 
 issuing standby command
outgoing cdb:  df 10 00 00 00 00 00 00 00 00 a0 e0
```
I guess that adding some detection logic is not quite easy.. If you'd like me to test something else, I'll be glad to help.

**Comment by adelolmo** [comment] 2023-10-28 14:14
After some investigation I think I came up with a way to identify if the jmicron controller is used. `hdparm` has special handling for that controller and now `hd-idle` should too.
Could you please test again this version (packages are re-uploaded): https://github.com/adelolmo/hd-idle/releases/tag/v1.21
You should try: `# hd-idle -d -t /dev/sda -c ata`

**Comment by amo13** [comment] 2023-10-29 11:02
Just tested. Unfortunately, it does not work. The output is:
```
 issuing standby command
outgoing cdb:  85 06 00 00 00 00 00 00 00 00 00 00 00 40 e0 00
```

**Comment by adelolmo** [comment] 2023-10-29 14:56
Thanks for testing it.
I changed the part that identifies the device based on the vendor and product. Hopefully this time works.
Could you please give it another try?

**Comment by amo13** [comment] 2023-10-29 15:52
Thank you too!
We're not quite there yet:
`# hd-idle -d -t /dev/sda -c ata`
```
APT: USB ID = 0x152d:0x2339 (0x0100)
APT: Unsupported device
 issuing standby command
outgoing cdb:  85 06 00 00 00 00 00 00 00 00 00 00 00 40 e0 00
```

I just cloned the repo and compiled with `make`.

**Comment by adelolmo** [comment] 2023-10-29 16:28
> I just cloned the repo and compiled with `make`.

Well, that's way faster :)

One more attempt. You can pull, compile the latest changes and try again.

If it doesn't work this time, could you also share the output of these commands:
* `# cat /sys/block/sda/../../../../../../idVendor`
* `# cat /sys/block/sda/../../../../../../idProduct`
* `# cat /sys/block/sda/../../../../../../bcdDevice`

If it doesn't find the file you might have to change the relative path:
eg. `# cat /sys/block/sda/../../../../../idVendor` (with 5 path jumps)
eg. `# cat /sys/block/sda/../../../../../../../idVendor` (with 7 path jumps)

**Comment by amo13** [comment] 2023-10-29 16:33
Fantastic, it works now! 
Thank you

**Comment by adelolmo** [comment] 2023-10-29 17:17
This one was fun to get working, but I'm glad it's now done :sweat_smile: 
Closing now.

**Closed by adelolmo** 2023-10-29 17:17 UTC
Labels: bug
